nelmio_api_doc:
    documentation:
        info:
            title: JWT API
            description: Este es el RESTful API de JWT
            version: 1.0.0
    routes: # to filter documented routes
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
